<?php

namespace {{ ESbuilderNamespace }};

use Framework\Model\Model;

class {{ ESbuilderName }} extends Model
{
    // Model generated with ESBuilder !

    /**
     * Table from database that will be used by Model
     *
     * @var string
     */
    protected $table = "{{ ESbuilderModelTable }}";

    /**
     *  Columns from database that will be used by Model
     *
     * @var array
     */
    protected $columns = [];
}