<?php

namespace Framework\Command;

use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;


class ControllerCommand extends Command
{
    const PATH_TO_CONTROLLER = $_SERVER['DOCUMENT_ROOT'] . DIRECTORY_SEPARATOR . "app" . DIRECTORY_SEPARATOR . "controller";

    /**
     * @return void
     */
    protected function configure()
    {
        $this
            ->setName('controller')
            ->setDescription('Créé un controller.')
            ->addArgument(
                'name',
                InputArgument::REQUIRED,
                'Le nom du controller, qui est obligatoire.'
            )
        ;
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $name = $input->getArgument('name');

        // Le nom du controller doit exister sinon erreur
        if (!$name){
            echo "<error>Vous devez indiquer le nom du controller si vous voulez le créer</error>";
        }
        else {
            // TODO : générer une classe PHP dans un autre dossier en appellant createController
        }

        parent::execute($input, $output); // TODO: Change the autogenerated stub
    }


    private function createController($name, $folder)
    {
        $namespaceFolder = '';
        $path_to_controller = $_SERVER['DOCUMENT_ROOT'] . DIRECTORY_SEPARATOR . "app" . DIRECTORY_SEPARATOR . "controller";

        // Le namespace par défaut dans le dossier controller, mais ça peut être ailleurs si on le précise avec "folder"
        if (isset($folder)){
            $namespaceFolder = DIRECTORY_SEPARATOR . trim($folder);

            // On va créér le dossier s'il n'existe pas déjà
            if (!file_exists($path_to_controller . $folder)){
                mkdir($path_to_controller . $folder, 0777, true);
            }
        }

        $namespace = "namespace App\controller" . $namespaceFolder . ";";

        // On créé le fichier PHP qui sera le controller et on y ajoute les lignes de base
        file_put_contents($name . "Controller", );
    }
}